set(_CATKIN_CURRENT_PACKAGE "race")
set(race_MAINTAINER "paritoshkelkar <paritoshkelkar@todo.todo>")
set(race_DEPRECATED "")
set(race_VERSION "0.0.0")
set(race_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "std_msgs")
set(race_RUN_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(race_BUILDTOOL_DEPENDS "catkin")